# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mk4BJxL32_0Jee_1OhUfcHkfjEQVVawd
"""

# Question 1
paragraph = "Python is a great language!\", said Fred. I don\"'t ever remember having this much fun before."

print(paragraph)

# Question 2
def leap(year):
  if year%4==0:
    if year%100==0:
      if year%400==0:
        return True
  return False;

leap(1900)

# Question 4
friendlist = ["aashish", "Punir", "Bibek", "Aadil", "Karan", "Madan", "Pooja", "Utkal", "Sabin", "Mahima", "Mahsika", "Aayush", "Mikal"]
friendlist.sort();
print(friendlist)

print("First and Second list members are: "+ friendlist[0]+" and "+ friendlist[1])

tup =("manish", "manandhar", 24);
lst = []
lst.append(tup)
print(lst)

tup1=("pawan", "KC", 25)
lst.append(tup1)

tup2=("john", "farnad", 33)
lst.append(tup2)

lst

lst.sort()

print(lst)

#Question 5 
def func(lst):
  return lst[2]
# func("man")
(lst.sort(key=func))
lst

# Question 6
lst_friends=["aashish", "Punir", "Bibek", "Aadil", "Karan", "Madan", "Pooja", "Utkal", "Sabin", "Mahima", "Mahsika", "Aayush", "Mikal"];
if "John" in lst_friends:
  print("Found")
else:
  print("Not Found")

# Question 7
def check(tup_list):
  avg=0;
  for i in range(0, len(tup_list)):
    
    if (tup_list[i][2] != None):
      
      avg=avg+ tup_list[i][2]
      # print(avg)
  avg = avg/len(tup_list)

  for j in tup_list:
    if j[2]>avg:
      print(j[0], ": Older")
    else:
      print(j[0], ": Younger")
    
  print(avg)

lst=[('pawan', 'KC', 25), ('john', 'farnad', 33), ('manish', 'manandhar', 24),("sagar", "Gautum", 33)]

check(lst)

# Question 8
def Prime(num):
  if num<=1:
    return False
  else:
    for i in range(2, num):
      if num%i==0:
        return False
    else:
        return True
      # break;

Prime(97)

# Question12 
def checkpalandrome(num):
  if num[::1]==num[::-1]:
    return True
  else:
    return False

checkpalandrome("aaaa")

# Question 10
from functools import reduce
string="ThisIsCamelCased"
# print(string.split(string.upper()))
def Case(camel_str):
  return reduce(lambda x,y: x+('_' if y.isupper() else "")+y, string).lower()
Case(string)

# question 11
variable = tuple("readme.txt")
n= len(variable)
x= slice(n-3,n)
y = slice(0,n-4)
extension = variable[x]
without_extension =  variable[y]

# print(extension)
("").join(extension)

("").join(without_extension)

# Question 13
import csv
with open('read.csv', 'w', newline="") as file:
  writer=csv.writer(file)
  writer.writerow(["name", "address", "age"])
  writer.writerow(["George", "4312 Abbey Road ", 22])
  writer.writerow(["John", "54 Love Ave", 21])

try:
  f = open("read.csv")
finally:
  f.close()

# Question 14
import csv
filename = 'read.csv'
with open(filename, 'r') as data:
  # csv_file = csv.DictReader(data)
  # for row in csv_file:
  #   print(dict(row))
  for line in csv.DictReader(data):
    print(dict(line))

# Question 15
class banking:
  def __init__(self, username, address, contact, amount, firstname, lastname):
    self.username = username
    self.address = address
    self.contact = contact
    self.amount = amount
    self.firstname= firstname
    self.lastname = lastname


  def Total_amount(self):
    print("my total amount:" , self.amount)
  def information(self):
    print("My fullname :"+ self.firstname +" "+ self.lastname)

  def address1(self):
    print("Address:"+ self.address )


Customer = banking("manishsayamee", "Banepa", 98346526272, 63000, "manish", "Manandhar")

Customer.address1()

# Question 17
class Calculator:
  def __init__(self, x,y):
    self.x = x
    self.y = y
  def add(self):
    return self.x+self.y
  def substract(self):
    return (self.x-self.y)
  def multiply(self):
    return self.x*self.y
  def division(self):
    return self.x/self.y

a= int(input("Enter the first number: "));
b =int(input("ENter the Second number: "));
calc = Calculator(a,b)
# select = 1;
# while select!=0:
print("0.Exits")
print("1.Add")
print("2.substraction")
print("3.multiply")
print("4.Division")

select = int(input("Enter the selector: "))
if select ==1:
  print("Result:" , calc.add())
elif select ==2:
  print("Result: ", calc.substract())
elif select ==3:
  print("Result: ", calc.multiply())
elif select==4:
  print("Result: ", calc.division())
elif select ==0:
  print("Exiting")
else:
  print("Invalid")

# Question 18
import json
# Serialization
data={
    'student':{
        "name":"Manish",
        "Age":24
    }
}
with open("data_file.json","w") as write_file:
  json.dump(data, write_file)

# OR
# json_string= json.dumps(data)

# deserialization|
json_string = json.dumps(data)

class check:
  def __init__(self,string):
    self.string = string

  def valid(self):
    if self.string[::1]==self.string[::-1]:
      return True
    else:
      return False
input_str = str(input("Enter the paranthesis: "))
obj = check(input_str)
obj.valid()

# Question 19
class solution:
   def valid_parenthese(self, str1):
        stack, pchar = [], {"(": ")", "{": "}", "[": "]"}
        for parenthese in str1:
            if parenthese in pchar:
                stack.append(parenthese)
            elif len(stack) == 0 or pchar[stack.pop()] != parenthese:
                return False
        return len(stack) == 0

solution1 = solution()
solution1.valid_parenthese('(){}{{}}')

# Question 20
class zero_list:
 def threeSum(self, nums):
        nums, result, i = sorted(nums), [], 0
        while i < len(nums) - 2:
            j, k = i + 1, len(nums) - 1
            while j < k:
                if nums[i] + nums[j] + nums[k] < 0:
                    j += 1
                elif nums[i] + nums[j] + nums[k] > 0:
                    k -= 1
                else:
                    result.append([nums[i], nums[j], nums[k]])
                    j, k = j + 1, k - 1
                    while j < k and nums[j] == nums[j - 1]:
                        j += 1
                    while j < k and nums[k] == nums[k + 1]:
                        k -= 1
            i += 1
            while i < len(nums) - 2 and nums[i] == nums[i - 1]:
                i += 1
        return result

print(zero_list().threeSum([-25, -10, -7, -3, 2, 4, 8, 10]))

